### ISSUE TITLE
cant hard reset or soft reset after flashing vanir and googls apps doesn't work

### ISSUE THREAD

**Issue by ihteshamraza** [VanirAOSP/device_lge_f320#2]
I have installed vanir on my lg g2 f320l, i didn't wipe all the data after flashing the rom, but now google play services keep on saying that i need to update them, cant use play store or any other app, and others apps keep crashing, cant soft reset, it gets stuck in  recovery and keeps on restart and shows only recovery logo and goes back to loop, cant boot into recovery r reset boot either i have tried all combinations, im just stuck with it,

**Comment by nuclearmistake** [comment]
whose gapps?

**Comment by nuclearmistake** [comment]
If your prior rom was not vanir, then not wiping data is definitely your problem... try to install recovery as if you were doing so for the first time, then recovery should work.
 if you'd rather NOT wipe data, I would advise trying to reinstall your previous ROM or restore a backup.

**Comment by ihteshamraza** [comment]
i already have twrp recovery installed, but problem is i can't boot into recovery, i have tried almost every combination. i think i have to go back to stock firmware because this rom has bugs too. whenever i open camera it reboots.

**Comment by nuclearmistake** [comment]
Without wiping data first, LOL YOU BET THERE ARE BUGS. That's why a data wipe is required when switching from other ROMs.

Recovery-wise, turn on developer options (7 clicks on buildid in About Phone in Settings), then turn on ADB debugging. Plug it into your PC and type "adb reboot recovery". That'll get you into recovery.

Once there, if you choose to continue running Vanir, follow the fresh install procedure. wipe system(to remove old copies of gapp apps)+data (old rom's app's data), install vanir, install gapps, and report issues that might reveal themselves at that time.

**Comment by ihteshamraza** [comment]
can you provide a link to appropriate gapps for lg g2 f320l korean. prior rom is f320llc stock.
